services:
  xlada-node:
    image: ghcr.io/xray-panel/node:latest
    container_name: xlada-node
    hostname: xlada-node
    network_mode: host
    restart: always
    cap_add:
      - NET_ADMIN
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    environment:
      - NODE_PORT=2222
      - SECRET_KEY=""
