services:
  remnawave-node-local:
    container_name: xpanel-node-local
    hostname: xpanel-node-local
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        INTEGRATIONS: ${INTEGRATIONS:-}
    networks:
      - remnawave-node-dev
    ports:
      - '11000:11000'
    env_file:
      - .env

networks:
  remnawave-node-dev:
    external: false
